// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Context;

public partial class Item
{
    public string ItemId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public double? Price { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Categorydetail> Categorydetails { get; set; } = new List<Categorydetail>();
}