// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Context;

public partial class Memberpackage
{
    public string MemberTypeId { get; set; }

    public string NameType { get; set; }

    public double? Price { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}