// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Context;

public partial class Plantedlog
{
    public string UserId { get; set; }

    public string ItemId { get; set; }

    public string Status { get; set; }

    public string Id { get; set; }

    public virtual Item Item { get; set; }

    public virtual User User { get; set; }
}