// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Context;

public partial class Scene
{
    public string UserId { get; set; }

    public string Status { get; set; }

    public DateTime? DateSave { get; set; }
}