// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Context;

public partial class Usertool
{
    public string UserId { get; set; }

    public string ToolsId { get; set; }

    public int? Quantity { get; set; }

    public virtual User User { get; set; }
}